package finalProject;

import javax.swing.JRadioButton;
/**
 * The Main Menu, here the user chooses either 1 player (against the computer) or 2 player
 */
public class MainMenu extends javax.swing.JFrame {
    // Member
    private KommandQuest driver;
    // Constructor
    public MainMenu(KommandQuest driver) {
        this.driver = driver;
        setSize(632, 435);
        setLocationRelativeTo(null);
        initComponents();
    }
    // Getters/Setters
    public JRadioButton getPlayerRadioOne() {
        return PlayerRadioOne;
    }
    /**
     * Note: The initComponents method and java.swing variables declared at the bottom were generated by the NetBeans IDE via the Design mode
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerRadioBtnGroup = new javax.swing.ButtonGroup();
        MainMenuTitle = new javax.swing.JLabel();
        MainMenuWelcome = new javax.swing.JLabel();
        BeginBtn = new javax.swing.JButton();
        PlayerRadioOne = new javax.swing.JRadioButton();
        PlayerRadioTwo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kommand Quest Main Menu");
        setSize(new java.awt.Dimension(600, 500));

        MainMenuTitle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        MainMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenuTitle.setText("╰（‵□′）╯  Kommand Quest Simulator  ╰(*°▽°*)╯");
        MainMenuTitle.setAlignmentY(0.0F);

        MainMenuWelcome.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        MainMenuWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainMenuWelcome.setText("Welcome to");
        MainMenuWelcome.setAlignmentY(0.0F);

        BeginBtn.setText("Begin");
        BeginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginBtnActionPerformed(evt);
            }
        });

        PlayerRadioBtnGroup.add(PlayerRadioOne);
        PlayerRadioOne.setSelected(true);
        PlayerRadioOne.setText("1 Player");

        PlayerRadioBtnGroup.add(PlayerRadioTwo);
        PlayerRadioTwo.setText("2 Player");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(MainMenuWelcome)
                    .addComponent(BeginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainMenuTitle)
                    .addComponent(PlayerRadioOne)
                    .addComponent(PlayerRadioTwo))
                .addGap(118, 118, 118))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MainMenuTitle, MainMenuWelcome});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(MainMenuWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PlayerRadioOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerRadioTwo)
                .addGap(34, 34, 34)
                .addComponent(BeginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(130, 130, 130))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Closes current window, opens the Army Selection Window
    * @param evt
    */
    private void BeginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginBtnActionPerformed
        driver.getPlayerSettings().setIsOnePlayer(getPlayerRadioOne().isSelected());
        driver.openArmySelection();
        this.dispose();
    }//GEN-LAST:event_BeginBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeginBtn;
    private javax.swing.JLabel MainMenuTitle;
    private javax.swing.JLabel MainMenuWelcome;
    private javax.swing.ButtonGroup PlayerRadioBtnGroup;
    private javax.swing.JRadioButton PlayerRadioOne;
    private javax.swing.JRadioButton PlayerRadioTwo;
    // End of variables declaration//GEN-END:variables

}
