package finalProject;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LaunchScreen extends javax.swing.JFrame {

    /**
     * Creates new form LaunchScreen
     */
    public LaunchScreen() {
        setUndecorated(true); // Removes the Windows buttons (close, minimize, ect...)
        setSize(400, 300); // Must be here to center screen for some reason, along with...
        setLocationRelativeTo(null); // Opens in middle of screen
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        Timer LaunchTitleTimer = new Timer(40, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                dispose(); // Close launch screen
//                new MainMenu().setVisible(true); // Open main menu
//            }
//        });
//        new Timer(2000, e -> LaunchTitleTimer.start()).start();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LaunchTitle = new javax.swing.JLabel();
        LaunchAuthor = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LaunchTitle.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        LaunchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LaunchTitle.setText("╰（‵□′）╯  Kommand Quest Simulator  ╰(*°▽°*)╯");
        LaunchTitle.setAlignmentY(0.0F);

        LaunchAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LaunchAuthor.setText("Author: Elijah Morishita");
        LaunchAuthor.setAlignmentY(0.0F);

        Version.setText("Version 1.0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Version)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(LaunchTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LaunchAuthor))
                        .addGap(40, 40, 40))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LaunchAuthor, LaunchTitle});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(LaunchTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LaunchAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(Version)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LaunchAuthor;
    private javax.swing.JLabel LaunchTitle;
    private javax.swing.JLabel Version;
    // End of variables declaration//GEN-END:variables

}
